# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


def file_open(fpath):
    try:
        with open(fpath, 'r') as f:
            return f.read()
    except:
        pass


class Ui_SecondWindow(object):
    def setupUi(self, MainWindow, txt_hash, fpath):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.plainTextEdit.appendPlainText(str(txt_hash))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow, fpath)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, fpath):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hash File"))
        self.label_2.setText(_translate("MainWindow", f"Contents of {fpath}"))
        self.label.setText(_translate("MainWindow", "Copy and paste the original hash to the app."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(MainWindow,None,None)
    MainWindow.show()
    sys.exit(app.exec_())
